### PR TITLE
dark-mode-charles

### PR DESCRIPTION
**Pull request by Yuxuan-Wu**
## Feature/Change Description
Dark mode for dashboard main page

## Developer Contributions
@Yuxuan-Wu 

## Dependencies
#111

### CODE REVIEW

**Review by mottur — DISMISSED** [review]
Dark mode style, icon, and functionality implemented. Approved.

**Comment by sbogh** [comment]
@Yuxuan-Wu resolve merge conflicts (pull new changes from release) and re-request

**Review by sbogh — CHANGES_REQUESTED** [review]
Code looks good, just need to resolve conflicts and you're good. Nice work!

**Comment by Yuxuan-Wu** [comment]
> One thing to note, when the DuckyAI page is live, we want to make sure we maintain dark mode state. Right now when you click the dummy link dark mode is reset

I can make an update in a later PR to solve this issue once the version stablizes

**Review by sbogh — APPROVED** [review]

**Pull request merged**
