### PR TITLE
custom-links-sravanthi

### PR DESCRIPTION
**Pull request by ChandraSravanthiKaki**
## Feature/Change Description

- **Add Custom Links Feature**: 
  - Implemented a new feature to allow users to add custom links to the dashboard.
  - Added an **"Add Link"** button between the "Delete" button and the "Links" title.

- **Popup for Link Adding**:
  - Clicking the **"Add Link"** button opens a popup modal at the center of the screen.
  - Users can enter a **link title** and **URL** in the modal.
  - Upon clicking **"Save"**, the link is added to the link list below.

- **Styling**:
  - The added link is styled with **green text**.
  - Links change color on hover for better UX.

- **Delete Functionality**:
  - Each added link includes a **"Delete"** button.
  - Users can click the **"Delete"** button to remove unwanted links from the list.

- **Chatbot Functionality**:
  - created a chatbot UI for the users to intreact with the chatbot

## Developer Contributions:
@davidtso1219

## Dependencies:
- No dependencies

### CODE REVIEW

**Comment by sbogh** [comment]
@ChandraSravanthiKaki we should be checking to see if a URL is of proper form. Right now if I enter dummy data it will append that to our site URL and take you to that page (which would be bad in case a user was able to access a page they shouldn't be able to see)

Example:

If I enter "blah" in the URL area the link is "https://dev-sravanthi.group10-esc012.pages.dev/blah"

https://www.freecodecamp.org/news/check-if-a-javascript-string-is-a-url/

**Comment by sbogh** [comment]
@ChandraSravanthiKaki Additionally, there should be consistency in our popovers. You have an animation set for yours while the task one does not. I think we should remove the animation

https://github.com/user-attachments/assets/d448807a-1ceb-47eb-b210-d008ef76e190

**Comment by mottur** [comment]
@ChandraSravanthiKaki also, it doesn't match Kayla's Figma design found here: https://www.figma.com/design/vmR73ilvmkx0uk6126HwOk/CSE-210-Design?node-id=1629-363&node-type=canvas
- The delete button should be a pencil icon (the same as for edit task)
- The + button should have a circle around it
- There should be an option to add an icon
Please check this out and make sure that it matches!

**Review by mottur — CHANGES_REQUESTED** [review]
Please refer to our comments for base functionality changes.

**Comment by ChandraSravanthiKaki** [comment]
> @ChandraSravanthiKaki also, it doesn't match Kayla's Figma design found here: https://www.figma.com/design/vmR73ilvmkx0uk6126HwOk/CSE-210-Design?node-id=1629-363&node-type=canvas
> 
> * The delete button should be a pencil icon (the same as for edit task)
> * The + button should have a circle around it
> * There should be an option to add an icon
>   Please check this out and make sure that it matches!

Addressed.

**Comment by ChandraSravanthiKaki** [comment]
> Please refer to our comments above for base functionality changes.

Done. Thanks

**Comment by ChandraSravanthiKaki** [comment]
> @ChandraSravanthiKaki Additionally, there should be consistency in our popovers. You have an animation set for yours while the task one does not. I think we should remove the animation
> 
>  animation.mp4

I removed the animation

**Comment by ChandraSravanthiKaki** [comment]
> @ChandraSravanthiKaki we should be checking to see if a URL is of proper form. Right now if I enter dummy data it will append that to our site URL and take you to that page (which would be bad in case a user was able to access a page they shouldn't be able to see)
> 
> Example:
> 
> If I enter "blah" in the URL area the link is "https://dev-sravanthi.group10-esc012.pages.dev/blah"
> 
> https://www.freecodecamp.org/news/check-if-a-javascript-string-is-a-url/

Addressed

**Review by mottur — DISMISSED** [review]
- Pencil and + icons should be the same size.
- Left justify the icons for both the added links and the create link form please. They don't look that nice toward the center.
- Make the "Save Link" button the same color as David's "Save" for create task form. Same for the outlines/icons. In fact, you can probably copy his CSS for that button.
- Format of the PR description is still wrong. Please refer to a merged PR for proper formatting.

**Comment by sbogh** [comment]
@ChandraSravanthiKaki please handle an extra case where a URL may be of form "https://github.com" or "http://github.com" or "www.github.com" or "github.com"

currently only the form https:// is handled

**Comment by ChandraSravanthiKaki** [comment]
> * Pencil and + icons should be the same size.
> * Left justify the icons for both the added links and the create link form please. They don't look that nice toward the center.
> * Make the "Save Link" button the same color as David's "Save" for create task form. Same for the outlines/icons. In fact, you can probably copy his CSS for that button.
> * Format of the PR description is still wrong. Please refer to a merged PR for proper formatting.

I am trying to fix the pencil and + icons, but the icons vectors are of different sizes when downloaded from the figma design. So will try to fix it now.

I have tried to justify them to the left, but the problem is with scaling, as u can see when we scale the website, the whole part gets spoilt except for the links part. I felt scaling is a very big issue, but if not, let me know I will modify it. And regarding the icons in the form part, I tried to build on the design that David made, given he didn't add all this and the PR was approved, I felt u guys felt it was not needed. But if you guys want the inputs to have the icons (I feel it being synchronous thought out the website is better), let me know, I will try to add it.

I will change the Save Link color.

Regarding the PR, is the screenshot the only problem, I cant find others. I will definitely remove the screenshots. If there are others, let me know.

image
image

image

**Comment by mottur** [comment]
- We see the issue with scaling. Looks like the text size isn't responsive. So forget the left-justify for now. We might try to fix it later.
- You said that you didn't include the icons in the create link form? But I can see them in the preview, only for the relevant links section. Can you double check? Since David didn't include the icons, you can also remove them.
- There should be a Dependencies section but you have two Developer Contributions sections. Also the Feature/Change Description section should ideally include separate bullets. And yes, please remove screenshots.

**Comment by ChandraSravanthiKaki** [comment]
> @ChandraSravanthiKaki please handle an extra case where a URL may be of form "https://github.com" or "[http://github.com](https://github.com)" or "www.github.com" or "github.com"
> 
> currently only the form https:// is handled

Addressed. I think it should work properly now.

**Comment by ChandraSravanthiKaki** [comment]
> * We see the issue with scaling. Looks like the text size isn't responsive. So forget the left-justify icons for now. We might try to fix it later.
> * You said that you didn't include the icons in the create link form? But I can see them in the preview, only for the relevant links section. Can you double check? Since David didn't include the icons for the create task form, you can also remove them.
> * For the PR description, there should be a Dependencies section but you have two Developer Contributions sections. Also the Feature/Change Description section should ideally include separate bullets. And yes, please remove screenshots.
> * For the input fields in the create link form, the outlines seem to be the same color as the "Save Link" button (wrong color) so please fix those as well.

Hey Meghana,
I think I addressed all the comments. Please review and let me know if there is anything else to be changed.

**Review by mottur — DISMISSED** [review]
- PR description: can you remove the screenshots? Also use bullets for the feature description.
- I think the pencil should be a little smaller or the + should be a little bigger for them to be the same size. You can look at the personal tasks and compare the pencil to the check circle for an example.
- For some reason, we can add links with empty name fields. This should be invalid too.
- I noticed that after deleting a link, it's no longer on edit mode (x's disappear). I think it should remain on edit mode so that the user can delete multiple links without having to press the edit icon multiple times. Then they would press enter or the edit button again to exit edit mode.
- I also noticed that David's forms (create/edit/filter) are surrounded by a green outline. Can you replicate that for your create link form? Make sure it's the same color too, the outlines for the forms look a little lighter than the outlines for the sections of the page.
- If possible, can you use the trashcan icon that David uses for tasks instead of x's to delete the links? It will look more uniform that way.
- Also if possible, the create link form looks a little empty so can you add "Add Link" or something similar at the top of the form, in the same font that David uses for "Task Name" for his forms?

**Comment by sbogh** [comment]
The code does not handle "github.com" format links and returns invalid URL

Also, the "X" should be right aligned inside the cell when edit is enabled

**Comment by ChandraSravanthiKaki** [comment]
> * PR description: can you remove the screenshots? Also use bullets for the feature description.
> * I think the pencil should be a little smaller or the + should be a little bigger for them to be the same size. You can look at the personal tasks and compare the pencil to the check circle for an example.
> * For some reason, we can add links with empty name fields. This should be invalid too.
> * I noticed that after deleting a link, it's no longer on edit mode (x's disappear). I think it should remain on edit mode so that the user can delete multiple links without having to press the edit icon multiple times. Then they would press enter or the edit button again to exit edit mode.
> * I also noticed that David's forms (create/edit/filter) are surrounded by a green outline. Can you replicate that for your create link form? Make sure it's the same color too, the outlines for the forms look a little lighter than the outlines for the sections of the page.
> * If possible, can you use the trashcan icon that David uses for tasks instead of x's to delete the links? It will look more uniform that way.
> * Also if possible, the create link form looks a little empty so can you add "Add Link" or something similar at the top of the form, in the same font that David uses for "Task Name" for his forms?

1. PR description now doesn't have the screenhots, and has the description in bullets format
2. I think I reduced the size as much as I can and retaining the overall structure now.
3. Now add links won't take empty link name, it shows Invalid title.
4. Yes, now the form has a very light green outline, exactly what david used.
5. Yes, now I'm using trash can instead of the 'X' mark.
6. Done, I added the titles for each input field in the link form

**Comment by ChandraSravanthiKaki** [comment]
> The code does not handle "github.com" format links and returns invalid URL
> 
> Also, the "X" should be right aligned inside the cell when edit is enabled

Hey Shayan,
Now even github.com, amazon.com will work, https will work, www. will work. Made the necessary changes.
I right aligned the trashcan.

**Review by mottur — APPROVED** [review]
Chatbot functionality and custom links confirmed. Approved.

**Pull request merged**
